#生产环境配置

server:
  # 服务端口
  port: 5000

spring:
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    url: jdbc:mysql://47.96.125.127:3306/salt?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: qwe123
    driver-class-name: com.mysql.jdbc.Driver

# 开启权限拦截
auth:
  enabled: true

# 开启登录要求验证码
login-captcha:
  enabled: false
  secret: "m49CPM5ak@MDXTzbbT_ZEyMM3KBsBn!h"

# 开启请求日志记录
request-log:
  enabled: true



